package com.example.cscb07project.repositories;

import android.util.Log;

import com.example.cscb07project.entities.Activity;
import com.example.cscb07project.interfaces.ActivityInterface;
import com.google.android.gms.tasks.Task;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.ArrayList;
import java.util.List;

public class ActivityRepository implements ActivityInterface {
    private final DatabaseReference dbRef;

    public ActivityRepository(FirebaseDatabase rootRef) {
        this.dbRef = rootRef.getReference("activities");
    }

    public Task<Void> addActivity(Activity activity) {
        String activityId = dbRef.push().getKey(); // fetch autogenerated ID after every post
        if (activityId == null) throw new IllegalStateException();
        activity.setUserId(activityId);
        return dbRef.child(activityId).setValue(activity);
    }

    public Task<List<Activity>> getFirstTenActivities() {
        return dbRef.get().continueWith(snapshot -> {
            if (!snapshot.isSuccessful() || snapshot.getResult() == null) return null;
            List<Activity> activityList = new ArrayList<>();
            int counter = 0;
            if (snapshot.getResult().hasChildren()) {
                for (DataSnapshot commentSnapshot : snapshot.getResult().getChildren()) {
                    if (counter >= 10) break;
                    activityList.add(commentSnapshot.getValue(Activity.class));
                    counter++;
                }
                return activityList;
            }
            return null;
        });
    }

    public Task<Void> deleteActivityById(String activityId) {
        return dbRef.child(activityId).removeValue().addOnSuccessListener(snapshot -> {
            Log.d("delete from firebase", "successfully deleted activity with id: " + activityId);
        }).addOnFailureListener(e -> {
            Log.e("firebase error", "error from deleting activity with id: " + activityId);
        });
    }
}
