package com.example.cscb07project.repositories;

import android.util.Log;

import androidx.annotation.NonNull;

import com.example.cscb07project.entities.Artifact;
import com.example.cscb07project.entities.ExpandedView;
import com.example.cscb07project.entities.User;
import com.example.cscb07project.systems.FieldScraper;
import com.google.android.gms.tasks.Task;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

public class ArtifactRepository {
    private final DatabaseReference dbRef;
    private final ExpandedViewRepository expandedViewRepository;

    public ArtifactRepository(FirebaseDatabase rootRef) {
        this.dbRef = rootRef.getReference("artifacts");
        this.expandedViewRepository = new ExpandedViewRepository(rootRef);
    }
    public ArtifactRepository(FirebaseDatabase rootRef, ExpandedViewRepository expandedViewRepository) { // expected to use rootRef for expandedView
        this.dbRef = rootRef.getReference("artifacts");
        this.expandedViewRepository = expandedViewRepository;
    }

    // add user
    public Task<Void> addArtifact(Artifact artifact) {
        // assume it contains all keys as identified in the class
//        String lotNumber = dbRef.push().getKey(); // fetch autogenerated ID after every post
//        if (lotNumber == null) throw new IllegalStateException();
//        artifact.setLotNumber(lotNumber);
        return dbRef.child(artifact.getLotNumber()).setValue(artifact).continueWithTask(snapshot -> {
            if (!snapshot.isSuccessful()) throw Objects.requireNonNull(snapshot.getException());
            return expandedViewRepository.addExpandedView(artifact.getLotNumber(), new ExpandedView(artifact.getLotNumber()));
        });
    }

    public void scrapeFieldValues(String key, FieldScraper callback){
        dbRef.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot snapshot) {
                Set<String> values = new HashSet<>(); // Use hashset to get O(1) Membership checks.

                for (DataSnapshot artifact : snapshot.getChildren()){ // Assuming we pull artifacts
                    String value = artifact.child(key).getValue(String.class);

                    if (value != null){
                        values.add(value);
                    }
                }

                callback.onResult(new ArrayList<>(values)); //CONVERT Hashset to be parseable by adapter.
            }

            @Override
            public void onCancelled(@NonNull DatabaseError error) {
                callback.onError(error);
            }
        });

    }

    public Task<Artifact> getArtifactByLotNumber(String lotNumber) {
        return dbRef.child(lotNumber).get().continueWith(snapshot -> {
            if (snapshot.getResult() != null) {
                return snapshot.getResult().getValue(Artifact.class);
            }
            return null;
        });
//
//        return dbRef.orderByChild("lotNumber").equalTo(lotNumber).get().continueWith(snapshot -> {
//            if (!snapshot.isSuccessful() || snapshot.getResult() == null) {
//                return null;
//            }
//            if (snapshot.getResult().hasChildren()) { // since get() returns a list, iterate through list to find matching
//                for (DataSnapshot artifactSnapshot : snapshot.getResult().getChildren()) {
//                    return artifactSnapshot.getValue(Artifact.class);
//                }
//            }
//            return null;
//        });
    }


    public Task<Void> updateArtifact(Artifact artifact) {
//        return dbRef.child(artifact.getArtifactId()).updateChildren(artifact.toMap());
        return dbRef.child(artifact.getLotNumber()).updateChildren(artifact.toMap());
    }

    public Task<Void> deleteArtifactByLotNumber(String lotNumber) {
//        return dbRef.orderByChild("lotNumber").equalTo(lotNumber).get().continueWithTask(snapshot -> {
//            if (!snapshot.isSuccessful() || snapshot.getResult() == null) {
//                return null;
//            }
//            return snapshot.getResult().getChildren().iterator().next().getRef().removeValue().continueWithTask(task -> {
//                if (!snapshot.isSuccessful()) throw Objects.requireNonNull(snapshot.getException());
//                Log.d("delete from firebase", "successfully deleted expanded view with id: " + lotNumber);
//                return expandedViewRepository.deleteExpandedViewByLotNumber(lotNumber).addOnSuccessListener(task2 -> {
//                    Log.d("delete from firebase", "successfully deleted artifact with id: " + lotNumber);
//                }).addOnFailureListener(e -> {
//                    Log.e("firebase error", "error from deleting artifact with id: " + lotNumber);
//                });
//            });
//        });


        return dbRef.child(lotNumber).removeValue().continueWithTask(snapshot -> {
            if (!snapshot.isSuccessful()) throw Objects.requireNonNull(snapshot.getException());
            return expandedViewRepository.deleteExpandedViewByLotNumber(lotNumber);

        }).addOnSuccessListener(snapshot -> {
            Log.d("delete from firebase", "successfully deleted artifact with id: " + lotNumber);
        }).addOnFailureListener(e -> {
            Log.e("firebase error", "error from deleting artifact with id: " + lotNumber);
        });
    }
}
