package com.example.cscb07project.repositories;

import android.util.Log;

import com.example.cscb07project.entities.Artifact;
import com.example.cscb07project.entities.ExpandedView;
import com.example.cscb07project.entities.User;
import com.google.android.gms.tasks.Task;
import com.google.android.gms.tasks.Tasks;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.Objects;

public class ArtifactRepository {
    private final DatabaseReference dbRef;
    private final ExpandedViewRepository expandedViewRepository;

    public ArtifactRepository(FirebaseDatabase rootRef, ExpandedViewRepository expandedViewRepository) { // expected to use rootRef for expandedView
        this.dbRef = rootRef.getReference("artifacts");
        this.expandedViewRepository = expandedViewRepository;
    }

    // add user
    public Task<Void> addArtifact(Artifact artifact) {
        // assume it contains all keys as identified in the class
//        String lotNumber = dbRef.push().getKey(); // fetch autogenerated ID after every post
//        if (lotNumber == null) throw new IllegalStateException();
//        artifact.setLotNumber(lotNumber);
        return dbRef.child(artifact.getLotNumber()).setValue(artifact).continueWithTask(snapshot -> {
            if (!snapshot.isSuccessful()) throw Objects.requireNonNull(snapshot.getException());
            return expandedViewRepository.addExpandedView(artifact.getLotNumber(), new ExpandedView(artifact.getLotNumber(), 0));
        });
    }

    public Task<Artifact> getArtifactByLotNumber(String lotNumber) {
        return dbRef.child(lotNumber).get().continueWith(snapshot -> {
            if (snapshot.getResult() != null) {
                return snapshot.getResult().getValue(Artifact.class);
            }
            return null;
        });
    }

    public Task<Void> updateArtifact(Artifact artifact) {
        return dbRef.child(artifact.getLotNumber()).updateChildren(artifact.toMap());
    }

    public Task<Void> deleteArtifactByLotNumber(String lotNumber) {
        return dbRef.child(lotNumber).removeValue().continueWithTask(snapshot -> {
            if (!snapshot.isSuccessful()) throw Objects.requireNonNull(snapshot.getException());
            return expandedViewRepository.deleteExpandedViewByLotNumber(lotNumber);

        }).addOnSuccessListener(snapshot -> {
            Log.d("delete from firebase", "successfully deleted artifact with id: " + lotNumber);
        }).addOnFailureListener(e -> {
            Log.e("firebase error", "error from deleting artifact with id: " + lotNumber);
        });
    }
}
