package com.example.cscb07project.repositories;

import android.util.Log;

import com.example.cscb07project.entities.Artifact;
import com.example.cscb07project.entities.Comment;
import com.example.cscb07project.entities.ExpandedView;
import com.example.cscb07project.interfaces.ExpandedViewInterface;
import com.google.android.gms.tasks.Task;
import com.google.android.gms.tasks.Tasks;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ServerValue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ExpandedViewRepository implements ExpandedViewInterface {
    // also for Comment repository
    private final DatabaseReference dbRefEx;
    private final DatabaseReference dbRefCo;

    public ExpandedViewRepository(FirebaseDatabase rootRef) {
        this.dbRefEx = rootRef.getReference("expandedViews");
        this.dbRefCo = rootRef.getReference("comments");
    }

    @Override
    public Task<Void> addExpandedView(ExpandedView expandedView) {
        String expandedViewId = dbRefEx.push().getKey(); // fetch autogenerated ID after every post
        if (expandedViewId == null) throw new IllegalStateException();
        expandedView.setExpandedViewId(expandedViewId);
        return dbRefEx.child(expandedViewId).setValue(expandedView);
    }

    @Override
    public Task<Void> addComment(Comment comment) {
        String commentId = dbRefCo.push().getKey();
        if (commentId == null) throw new IllegalStateException();
        comment.setCommentId(commentId);
        return dbRefCo.child(commentId).setValue(comment);
    }

    @Override
    public Task<Void> updateComment(Comment comment) {
        return dbRefCo.child(comment.getCommentId()).updateChildren(comment.toMap());
    }
    @Override
    public Task<Void> like(String userId, ExpandedView expandedView) {
        if (!isArtifactLikedByUser(userId, expandedView)) {
            Map<String, Object> updates = new HashMap<>();
            updates.put("likeNumber", ServerValue.increment(1));
            updates.put("likes/" + userId, true); // make a new path in lotNumber/likes/userId

            return dbRefEx.child(expandedView.getExpandedViewId()).updateChildren(updates).addOnSuccessListener(task -> {
                expandedView.setLikeNumber(expandedView.getLikeNumber() + 1);
                if (expandedView.getLikes() == null) {
                    expandedView.setLikes(new HashMap<>());
                }
                expandedView.getLikes().put(userId, true);
            });
        }
        return Tasks.forResult(null);
    }
    @Override
    public Task<Void> unlike(String userId, ExpandedView expandedView) {
        if (isArtifactLikedByUser(userId, expandedView)) {
            Map<String, Object> updates = new HashMap<>();
            updates.put("likeNumber", ServerValue.increment(-1));
            updates.put("likes/" + userId, null); // remove path lotNumber/likes/userId

            return dbRefEx.child(expandedView.getExpandedViewId()).updateChildren(updates).addOnSuccessListener(task -> {
                expandedView.setLikeNumber(expandedView.getLikeNumber() - 1);
                if (expandedView.getLikes() != null) {
                    expandedView.getLikes().remove(userId);
                }
            });
        }
        return Tasks.forResult(null);
    }
    @Override
    public boolean isArtifactLikedByUser(String userId, ExpandedView expandedView) {
        return expandedView.getLikes() != null && expandedView.getLikes().containsKey(userId);
    }

    @Override
    public Task<ExpandedView> getExpandedViewByLotNumber(String lotNumber) {
        return dbRefEx.orderByChild("lotNumber").equalTo(lotNumber).get().continueWith(snapshot -> {
            if (!snapshot.isSuccessful() || snapshot.getResult() == null) {
                return null;
            }
            if (snapshot.getResult().hasChildren()) { // since get() returns a list, iterate through list to find matching
                for (DataSnapshot expandedViewSnapshot : snapshot.getResult().getChildren()) {
                    return expandedViewSnapshot.getValue(ExpandedView.class);
                }
            }
            return null;
        });
    }

    @Override
    public Task<Comment> getCommentById(String lotNumber, String commentId) {
        return dbRefCo.child(commentId).get().continueWith(snapshot -> {
            if (snapshot.getResult() != null) {
                return snapshot.getResult().getValue(Comment.class);
            }
            return null;
        });
    }

    @Override
    public Task<List<Comment>> getCommentsByLotNumber(String lotNumber) {
        return dbRefCo.orderByChild("lotNumber").equalTo(lotNumber).get().continueWith(snapshot -> {
            if (!snapshot.isSuccessful() || snapshot.getResult() == null) {
                return null;
            }
            List<Comment> commentList = new ArrayList<>();
            if (snapshot.getResult().hasChildren()) {
                for (DataSnapshot commentSnapshot : snapshot.getResult().getChildren()) {
                    commentList.add(commentSnapshot.getValue(Comment.class));
                }
                return commentList;
            }
            return null;
        });
    }

    @Override
    public Task<Void> deleteCommentById(String commentId) {
        return dbRefCo.child(commentId).removeValue().addOnSuccessListener(snapshot -> {
            Log.d("delete from firebase", "successfully deleted comment with id: " + commentId);
        }).addOnFailureListener(e -> {
            Log.e("firebase error", "error from deleting comment with id: " + commentId);
        });
    }

    @Override
    public Task<Void> deleteExpandedViewByLotNumber(String lotNumber) {
        return dbRefEx.orderByChild("lotNumber").equalTo(lotNumber).get().continueWithTask(snapshot -> {
            if (!snapshot.isSuccessful() || snapshot.getResult() == null) {
                return null;
            }
            return snapshot.getResult().getChildren().iterator().next().getRef().removeValue().addOnSuccessListener(task -> {
                Log.d("delete from firebase", "successfully deleted expanded view with id: " + lotNumber);
            }).addOnFailureListener(e -> {
                Log.e("firebase error", "error from deleting expanded view with id: " + lotNumber);
            });
        });
    }
}
