package com.example.cscb07project.repositories;

import android.util.Log;

import androidx.annotation.NonNull;

import com.example.cscb07project.entities.User;
import com.google.android.gms.tasks.Task;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

public class UserRepository {
    private final DatabaseReference dbRefUs;
    private final DatabaseReference dbRefAd;

    public UserRepository(FirebaseDatabase rootRef) {
        this.dbRefUs = rootRef.getReference("users");
        this.dbRefAd = rootRef.getReference("admins");
    }

    // add user
    public Task<Void> addUser(User user) {
        String userId = dbRefUs.push().getKey(); // fetch autogenerated ID after every post
        if (userId == null) throw new IllegalStateException();
        user.setUserId(userId);
        return dbRefUs.child(userId).setValue(user);
    }

    public Task<Void> addUserWithId(User user, String userId) {
        return dbRefUs.child(userId).setValue(user);
    }

    // check if user is an admin
    public Task<Boolean> isAdmin(String userId) {
        return dbRefAd.child(userId).get().continueWith(snapshot -> {
            if (!snapshot.isSuccessful() || snapshot.getResult() == null)
                return snapshot.getResult() != null;
            return snapshot.getResult().child(userId).getValue(Boolean.class) != null;
        });
    }

    // get user by id
    public Task<User> getUserById(String userId) {
        return dbRefUs.child(userId).get().continueWith(snapshot -> {
            if (snapshot.getResult() != null) {
                return snapshot.getResult().getValue(User.class);
            }
            return null;
        });
    }

    public Task<User> getUserByEmail(String email) {
        return dbRefUs.orderByChild("email").equalTo(email).get().continueWith(snapshot -> {
            if (!snapshot.isSuccessful() || snapshot.getResult() == null) {
                return null;
            }
            if (snapshot.getResult().hasChildren()) { // since get() returns a list, iterate through list to find matching
                for (DataSnapshot userSnapshot : snapshot.getResult().getChildren()) {
                    return userSnapshot.getValue(User.class);
                }
            }
            return null;
        });
    }

    public Task<Void> updateUser(User user) {
        return dbRefUs.child(user.getUserId()).updateChildren(user.toMap());
    }

    public Task<Void> deleteUserById(String userId) {
        return dbRefUs.child(userId).removeValue().addOnSuccessListener(snapshot -> {
            Log.d("delete from firebase", "successfully deleted user with id: " + userId);
        }).addOnFailureListener(e -> {
            Log.e("firebase error", "error from deleting user with id: " + userId);
        });
    }
}
