package com.example.cscb07project.repositories;

import android.util.Log;

import androidx.annotation.NonNull;

import com.example.cscb07project.entities.User;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.android.gms.tasks.Tasks;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

public class UserRepository {
    private final DatabaseReference dbRefUs;
    private final DatabaseReference dbRefAd;

    public UserRepository(FirebaseDatabase rootRef) {
        this.dbRefUs = rootRef.getReference("users");
        this.dbRefAd = rootRef.getReference("admins");
    }

    // add user
    public Task<Void> addUser(User user) {
        String userId = dbRefUs.push().getKey(); // fetch autogenerated ID after every post
        if (userId == null) throw new IllegalStateException();
        user.setUserId(userId);
        return dbRefUs.child(userId).setValue(user);
    }

    public Task<Void> addAdmin(String userId) {
        Map<String, Boolean> map = new HashMap<String, Boolean>();
        map.put(userId, true);
        return dbRefAd.setValue(map);
    }

    // check ifAdmin
    public Task<Boolean> isAdmin(String userId) {
        return dbRefAd.child(userId).get().continueWith(snapshot -> {
            return snapshot.getResult() != null;
        });
    }

    // get user by id
    public Task<User> getUserById(String userId) {
        return dbRefUs.child(userId).get().continueWith(snapshot -> {
            if (snapshot.getResult() != null) {
                return new User(snapshot.getResult().child("userId").getValue(String.class),
                        snapshot.getResult().child("email").getValue(String.class),
                        snapshot.getResult().child("username").getValue(String.class),
                        snapshot.getResult().child("password").getValue(String.class));
            }
            return null;
        });
    }

    public Task<Void> deleteUserById(String userId) {
        return dbRefUs.child(userId).removeValue().continueWithTask(snapshot -> {
            if (!snapshot.isSuccessful()) throw Objects.requireNonNull(snapshot.getException());
            return isAdmin(userId); // if successful delete, pass this state to the next async task
        }).continueWithTask(snapshot -> { // performs task after previous is complete
            if (!snapshot.isSuccessful()) throw Objects.requireNonNull(snapshot.getException());
            boolean isAdmin = snapshot.getResult();
            if (isAdmin) {
                return dbRefAd.child(userId).removeValue();
            }
            return Tasks.forResult(null); // completed chain of tasks, must return something
        }).addOnSuccessListener(snapshot -> {
            Log.d("delete from firebase", "successfully deleted user with id: " + userId);
        }).addOnFailureListener(e -> {
            Log.e("firebase error", "error from deleting user with id: " + userId);
        });
    }
}
