package com.example.cscb07project.repositories;

import android.util.Log;

import androidx.annotation.NonNull;

import com.example.cscb07project.entities.User;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

public class UserRepository {
    private final DatabaseReference dbRefUs;
    private final DatabaseReference dbRefAd;

    public UserRepository(FirebaseDatabase rootRef) {
        this.dbRefUs = rootRef.getReference("users");
        this.dbRefAd = rootRef.getReference("admins");
    }

    // add user
    public void addUser(User user) {
        String userId = dbRefUs.push().getKey(); // fetch autogenerated ID after every post
        if (userId == null) throw new IllegalStateException();
        user.setUserId(userId);
        dbRefUs.child(userId).setValue(user);
    }

    // get all users - for testing purposes later

    // get user by id
    public Task<DataSnapshot> getUserById(String userId) {
        return dbRefUs.child(userId).get();
    }
}
