package com.example.cscb07project;

import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

public class UserRepository {
    private final DatabaseReference dbRef;

    public UserRepository() {
        this.dbRef = FirebaseDatabase.getInstance("https://cscb07-project-e0581-default-rtdb.firebaseio.com/").getReference("users");
    }

    // add user
    public void addUser(String email, String username, String password) {
        String userId = dbRef.push().getKey(); // fetch autogenerated ID after every post
        User user = new User(userId, email, username, password);
        if (userId != null) dbRef.child(userId).setValue(user);
        // so what if it is null? throw exception?
    }
}
